demo-player/src/main.rs, dotlottie-rs/src/lottie_renderer/mod.rs, dotlottie-rs/src/lottie_renderer/tests.rs, dotlottie-rs/src/thorvg.rs, web-example.html
Fixes:
- Ensure `tvg_canvas_clear(true)` is called before loading a new animation to free the pushed paints from memory. This prevents memory leaks when loading multiple animations.
- Modify the `thorvg::Animation` struct to own the raw pointer to the picture, resulting in all related picture methods being moved to the Animation struct. This also simplifies the API.
- The width and height of the background_color shape should match the canvas's width and height, not the picture's width and height.
- Resize the background_color shape on canvas resize.
=> fix: 🐛 ensure canvas is cleared before loading a new animation

demo-player/src/main.rs, dotlottie-rs/src/thorvg.rs
*issue*
When the `DotLottiePlayer` instance is dropped from memory and a new instance is created, there is a rapid increase in memory usage, resulting in a memory leak. 
*Solution*
Calling `tvg_canvas_clear(true)` should remove the paints instances from memory. Therefore, all that needs to be done is to invoke `tvg_animation_del` when the Animation instance is released.
Also ensure that `tvg_canvas_clear(true)` followed by `tvg_canvas_destroy` is called to drop the canvas properly. This will ensure that the `Animation`, `Canvas`, and any paints pushed to the canvas, such as `Picture` and `Background` shape, are completely freed from memory, and we don't have to drop them individually.
=> fix: 🐛 segmentation fault when LottieRender is dropped

dotlottie-fms/src/manifest.rs, dotlottie-fms/src/manifest_themes.rs, dotlottie-fms/src/tests/manifest/mod.rs
This pull request addresses an issue where the `themes` field in the manifest object was being serialized with an unnecessary extra array wrapper. The serialization process was mistakenly wrapping the already arrayed themes in an additional array, leading to incorrect JSON structure.
Changes Made:
- Updated the `to_json` method in the `Manifest` struct to ensure themes are directly serialized as an array of theme objects without an extra wrapping array. This adjustment aligns the serialization process with the expected JSON format.
=> fix: 🐛 unnecessary extra array wrapper in theme serialization

dotlottie-rs/src/thorvg.rs
ThorVG requires the engine's initialization and
termination functions to be called in pairs.
+ clear will be conducted by the thorvg
internally when it's terminated.
=> thorvg: terminate engine properly.

Makefile, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/tests/play_mode.rs
Changes: 
- updated `is_complete` method to return correct result on load for Bounce/ReverseBounce mode, and account for the direction to determine if an animation has completed or not in bounce modes. 
- updated related tests
fix #114
=> fix: 🐛 unexpected is_complete result for Bounce modes on load

demo-player/src/main.rs, dotlottie-ffi/emscripten_bindings.cpp, dotlottie-ffi/src/dotlottie_player.udl, dotlottie-ffi/src/dotlottie_player_cpp.udl, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/tests/theming.rs
Close #119 
I refer @theashraf implementation in #125.
=> feat: Add `active_theme_id` function

dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/tests/play.rs
**Context:**
This PR addresses an issue reported in dotlottie-web where calling `play` after `set_frame` fails to start the animation from the specified frame. Instead, the animation begins from the initial frame, disregarding the frame set by the user.
The underlying problem is within the `play` method, which incorrectly assumes that if the playback state is `Stopped`, it should always start from the initial frame, ignoring the current frame. This behavior is only appropriate if the animation has completed its cycle and then stopped.
**Changes:**
- Updated the `play` method to initiate from the initial frame only if the animation has completed, but not when it is merely stopped.
- Added several regression and integration tests for the `play` method to ensure:
- The animation resumes …
=> fix: 🐛 play() after set_frame() resets the animation

Makefile, dotlottie-ffi/Cargo.wasm.toml
**Context:**
- WASM bindings are generated from the C++ bindings created by `uniffi-bindgen-cpp`.
- `uniffi-bindgen-cpp` supports only `uniffi@v0.25.x`. Therefore, we need to dynamically downgrade the uniffi version from `v0.27` to `v0.25` when building for WASM.
**Changes:**
- Created `Cargo.wasm.toml`, which is a modified copy of the default `Cargo.toml`, but with `uniffi@v0.25` instead of `uniffi@v0.27`.
- Updated the Makefile to include two steps: `pre-make-wasm` and `post-make-wasm`. The `pre-make wasm` step copies the contents of `Cargo.wasm.toml` to the default `Cargo.toml`, and the `post-make-wasm` step cleans it up, restoring the original `Cargo.toml`.
> These changes will ensure that the WASM release assets function properly, eliminating the need to build WASM locally for …
=> ci: 🎡 use uniffi@0.25.3 for wasm target only

.mac-setup.sh, Makefile, dotlottie-ffi/Cargo.toml, dotlottie-ffi/emscripten_bindings.cpp
Changes: 
- Upgrade EMSDK to version 3.1.57 & uniffi-bindgen-cpp to version 0.6.0+v0.25.0
- Due to the upgrade, replace the deprecated `--embind-emit-tsd` option with `--emit-tsd`
- Due to the upgrade, an additional step has been added to the `mac-setup` to install npm packages in `EMSDK`. This is necessary for proper TypeScript file generation when targeting WebAssembly.
=> chore: 🤖 upgrade dependencies [emsdk@v3.1.57 - uniffi-bindgen-cpp@v0.6.0+v0.25.0]

dotlottie-ffi/src/dotlottie_player.udl, dotlottie-ffi/src/dotlottie_player_cpp.udl, dotlottie-fms/src/manifest_animation.rs, dotlottie-fms/src/tests/manifest/mod.rs, dotlottie-rs/src/dotlottie_player.rs
fix #150 
The `manifest.json` in the attached `problematic.zip` contains a speed property defined as a float number. The `dotlottie_fms` assumes the speed is a `u32`, causing a panic when loading this valid .lottie file.
[problematic.zip](https://github.com/LottieFiles/dotlottie-rs/files/15377948/problematic.zip)
=> fix: 🐛 .lottie file load failure with float speed property

.changeset/featplayback_segment_duration_getter.md, dotlottie-ffi/emscripten_bindings.cpp, dotlottie-ffi/src/dotlottie_player.udl, dotlottie-ffi/src/dotlottie_player_cpp.udl, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/tests/speed.rs
**Context:**
The current `duration()` method returns the duration of the entire animation. However, when the player is playing a specific segment or marker, there is no way to get the duration of the currently playing segment. This PR introduces the `segment_duration()` method, which returns the duration of the currently set segment if it exists. Otherwise, it returns the duration of the whole animation as defined in the Lottie JSON.
**Changes:**
- Added a new method called `segment_duration()`.
- Updated Uniffi bindings and UDL files.
- Updated Emscripten bindings.
- Updated tests.
**Related issue:** [LottieFiles/dotlottie-web#194](https://github.com/LottieFiles/dotlottie-web/issues/194)
=> feat(playback): 🎸 segment duration getter

.changeset/fixplayback_update_speed_causes_animation_frame_jump.md, dotlottie-rs/src/dotlottie_player.rs
fixes https://github.com/LottieFiles/dotlottie-web/issues/195
=> fix(playback): 🐛 update speed causes animation frame jump

.changeset/feat_add_tvg_canvas_set_viewport_integration_and_bindings.md, dotlottie-ffi/emscripten_bindings.cpp, dotlottie-ffi/src/dotlottie_player.udl, dotlottie-ffi/src/dotlottie_player_cpp.udl, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/src/lottie_renderer/mod.rs, dotlottie-rs/src/thorvg.rs, web-example.html
**Description:**
In ThorVG v0.13.5, the `tvg_canvas_set_viewport` API was introduced to define the rectangular area of the canvas that will be used for drawing operations. The specified viewport clips the rendering output to the boundaries of the rectangle. This change can improve rendering performance by rendering only within the visible canvas boundaries.
**Changes:**
- Added safe Rust bindings to ThorVG's `tvg_canvas_set_viewport`
- Integrated `tvg_canvas_set_viewport` in the DotLottie runtime
- Updated Uniffi bindings
- Updated Emscripten bindings
- Updated the web example
=> feat: 🎸 add tvg_canvas_set_viewport integration and bindings

dotlottie-ffi/emscripten_bindings.cpp, dotlottie-ffi/src/dotlottie_player.udl, dotlottie-ffi/src/dotlottie_player_cpp.udl, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/src/state_machine/mod.rs, dotlottie-rs/src/state_machine/parser/mod.rs, dotlottie-rs/src/state_machine/states/mod.rs, dotlottie-rs/tests/assets/pigeon_fsm.json, dotlottie-rs/tests/assets/pigeon_fsm_bool_eq_guard.json, dotlottie-rs/tests/assets/pigeon_fsm_eq_guard.json, dotlottie-rs/tests/assets/pigeon_fsm_gt_gte_guard.json, dotlottie-rs/tests/assets/pigeon_fsm_lt_lte_guard.json, dotlottie-rs/tests/assets/pigeon_fsm_ne_guard.json, dotlottie-rs/tests/state_machine.rs, dotlottie-rs/tests/state_machine_guards.rs, dotlottie-rs/tests/test_utils.rs, examples/demo-state-machine/src/main.rs, examples/demo-state-machine/src/pigeon_fsm.json
This PR adds:
- Possibility to add a state machine observer with the 3 event callbacks to listen to:
- `fn on_transition(&self, previous_state: &State, new_state: &State);`
- `fn on_state_entered(&self, entering_state: &State);`
- `fn on_state_exit(&self, leaving_state: &State);`
=> Feat/state machine–observer

dotlottie-fms/src/functions.rs
Context:
dotlottie player attempts to inline external assets if they exist by assuming that any asset with a "p" property (path property) requires inlining. However, there are instances where the Lottie JSON contains already embedded image assets within the .lottie file. Attempting to inline these already inlined assets corrupts the Lottie JSON, causing the player to fail to load the animation data properly.
Changes: 
- Added a check to skip the inlining process if the image asset is already inlined.
test .lottie
[3230094.zip](https://github.com/user-attachments/files/15782726/3230094.zip)
=> fix: 🐛 prevent inlining of already embedded image assets in .lottie

.github/workflows/build.yml
This pull request adds a new feature to our CI workflow, giving us more flexibility in configuring the build environment. With these changes, you can now specify the machine image version, Xcode version, and macOS SDK to use during the build process.
- Machine Selection: You can now choose the machine image version (e.g., macos-11, macos-12) before running the build.
- Xcode Version: Allows specifying which version of Xcode (e.g., Xcode_13.3.1.app) to use.
- macOS SDK: You can define the macOS SDK version (e.g., MacOSX12.3) for the build.
=> ci: 🎡 add flexible environment customization for build workflow

dotlottie-rs/src/dotlottie_player.rs
fixes a regression in the manifest_string method, which should return an empty string if the Option<Manifest> is None
=> fix: 🐛 manifest_string() panics when no manifest available

.changeset/chorewasm_reduce_wasm_binary_size.md, .github/workflows/check-pr.yaml, .mac-setup.sh, Makefile, dotlottie-ffi/Cargo.wasm.toml, web-example.html
This PR introduces optimizations to reduce the size of the WASM binary and the accompanying JavaScript glue code.
- **WASM Binary Optimization**:
- Applied the [`-Oz` flag](https://emscripten.org/docs/tools_reference/emcc.html#emcc-oz) with `emcc` for size optimization.
- Use the compact [emmalloc](https://emscripten.org/docs/tools_reference/settings_reference.html#malloc) allocator.
- Use the Rust nightly toolchain to remove location details and panic string formatting for a smaller binary size.
- **Current Size**: 1,245,102 bytes
- **New Size**: 1,099,243 bytes
- **Reduction**: ~142 KB
- **JavaScript Glue Optimization**:
- Enabled the [Closure Compiler](https://emscripten.org/docs/site/glossary.html#term-closure-compiler) with the `--closure=1` flag.
- **Current Size**: 67,964 bytes
- …
=> chore(wasm): 🤖 reduce WASM binary size

.mac-setup.sh
Meson automatically bumped to the latest version when using brew install, causing iOS to fail its build.
To fix this this PR reverts to the previous meson version the project has been using.
=> fix: iOS build issue caused by meson 1.5.0

dotlottie-rs/src/lottie_renderer/mod.rs
The canvas syncs before changing a target buffer.
https://github.com/thorvg/thorvg/issues/2580
=> fix: thorvg canvas resize problem.

.mac-setup.sh, Makefile, dotlottie-ffi/emscripten_bindings.cpp, dotlottie-rs/Cargo.toml
**Changes:**
- Updated the `instant` crate to version `0.1.13`.
- Fixed the `undefined symbol: _emscripten_get_now` issue by adding the necessary underscore prefix as a workaround.
- Upgrade Uniffi-bindgen-cpp to v0.6.0+v0.25.0
- Emscripten upgrade to v3.1.68
> This change allows the package to be publishable to crates.io, as crates with git dependencies cannot be published.
=> chore: fix undefined symbol _emscripten_get_now for wasm compatibility

.github/workflows/build.yml, .github/workflows/check-pr.yaml, .github/workflows/release.yaml, .mac-setup.sh
Changes:
- updated the `mac-setup.sh` script to configure the necessary toolchain based on the target platform (WASM, Apple, or Android). This optimization reduces CI build time when targeting a specific platform, such as WASM only.  
- upgraded the Meson version in `mac-setup.sh` to v1.6.0.  
- updated the build artifacts to use the latest macOS image for Android and WASM builds, as `macos-12` is now deprecated. 
test build: 
https://github.com/LottieFiles/dotlottie-rs/actions/runs/11926940801
=> chore: improve release & build artifacts workflow

.github/workflows/build.yml, .github/workflows/check-pr.yaml, .github/workflows/release.yaml, Makefile, dotlottie-ffi/Cargo.toml
Changes:
- Updated GitHub Actions to use the latest macOS version since macOS-12 has been deprecated.
- Ensured that native dependencies, and dotLottie-rs are built for the same minimum OS version. This is a potential fix for the issue: https://github.com/LottieFiles/dotlottie-ios/issues/9
=> fix: minimum deployment version of the iOS and MacOSX targets

.vscode/launch.json, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/src/lottie_renderer/mod.rs
Context:
The background shape is destroyed only when it is owned by the canvas and the canvas is cleared or destroyed
Leaks report: 
```
Process:         demo-player [20165]
Path:            /Users/USER/*/demo-player
Load Address:    0x1029d8000
Identifier:      demo-player
Version:         0
Code Type:       ARM64
Platform:        macOS
Parent Process:  leaks [20164]
Date/Time:       2025-01-11 22:59:19.593 +0700
Launch Time:     2025-01-11 22:59:06.200 +0700
OS Version:      macOS 14.5 (23F79)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 16.2 (16C5032a)
Physical footprint:         19.4M
Physical footprint (peak):  36.2M
Idle exit:                  untracked
----
leaks Report Version: 4.0, multi-line stacks …
```
=> fix: 🐛 memory leak when LottieRenderer is created

.github/workflows/check-pr.yaml, Makefile, dotlottie-ffi/Cargo.toml, dotlottie-ffi/Cargo.wasm.toml, dotlottie-rs/Cargo.toml, dotlottie-rs/build.rs, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/src/lottie_renderer/mod.rs, dotlottie-rs/src/lottie_renderer/renderer.rs, dotlottie-rs/src/lottie_renderer/thorvg.rs, examples/demo-player/Cargo.toml, examples/demo-state-machine/Cargo.toml, examples/demo-state-machine/src/bin/play-on-hover/play-on-hover.rs, examples/demo-state-machine/src/bin/star-rating/star-rating.rs
1. **Feature Flags for `thorvg` Versions**
- Added two feature flags: `thorvg-v1` and `thorvg-v0`.
- These allow us to maintain compatibility with `thorvg` v0.x.x, as binaries for Linux, Windows, and macOS from the Conan registry currently only support v0.
- `thorvg-v1` is a pre-release version and is not yet stable or available on Conan.
2. **Default Configuration**
- By default, the `thorvg-v0` flag is enabled for the FFI, unless explicitly specified otherwise.
3. **Build Target Differences**
- WebAssembly (WASM), Android, and Apple builds use `thorvg-v1`.
- Native dependencies (Linux/Windows/macOS) use `thorvg-v0
WASM/APPLE/ANDROID artifacts -> https://github.com/LottieFiles/dotlottie-rs/actions/runs/12764709359
=> feat: upgrade thorvg v1.0-pre10

dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/src/state_machine_engine/actions/mod.rs, dotlottie-rs/tests/frame_interpolation.rs, dotlottie-rs/tests/play.rs, dotlottie-rs/tests/play_mode.rs, dotlottie-rs/tests/stop.rs
Changes:
- Made total_frames() return the actual total frame count without adjustments
- Consistently applied the -1.0 offset where needed (end frame calculations, bounds checking)
- Updated all tests to properly check frame boundaries and end conditions
- Ensured all animation modes (normal, reverse, bounce) use consistent frame boundaries
=> fix: return unadjusted frame count from total_frames() 

.github/workflows/build.yml, Makefile, dotlottie-ffi/assets/android/build.gradle.kts
related https://github.com/LottieFiles/dotlottie-android/issues/65
> Note: Building for 32-bit ABIs is broken when targeting API level 21. This solution has been applied: https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md#32_bit-and
Build artifacts: https://github.com/LottieFiles/dotlottie-rs/actions/runs/15376509098/job/43261874759
=> feat: target Android API level 21 for wider device support

.changeset/thorvg_internal_codecs.md, .gitmodules, .mac-setup.sh, Makefile, dotlottie-rs/build.rs
Changes:
Removed external image format dependencies in favor of ThorVG's internal implementations for PNG, WebP, and JPEG decoding.
**Removed submodules:**
* `libpng`
* `libwebp`
* `libjpeg-turbo`
* `zlib`
* `ios-cmake`
Why ?:
* ThorVG’s built-in decoders are size-optimized, which results in smaller shared libraries for Android and iOS
* Fewer external dependencies simplify the build process and reduce failure points
* Lower maintenance burden for dependency versioning
* Reduced toolchain setup requirements
* Faster compilation across target architectures
* Easier support for new platforms and environments
Build Artifacts: https://github.com/LottieFiles/dotlottie-rs/actions/runs/15378116508
=> refactor: use thorvg internal image codecs, remove external deps

.changeset/refactor_simplify_error_handling_and_remove_unnecessary_error_details.md, dotlottie-rs/Cargo.toml, dotlottie-rs/src/dotlottie_player.rs, dotlottie-rs/src/fms/dolottie_manager.rs, dotlottie-rs/src/fms/errors.rs, dotlottie-rs/src/fms/functions.rs, dotlottie-rs/src/lottie_renderer/mod.rs, dotlottie-rs/src/lottie_renderer/renderer.rs, dotlottie-rs/src/lottie_renderer/thorvg.rs, dotlottie-rs/src/state_machine_engine/actions/mod.rs, dotlottie-rs/src/state_machine_engine/errors.rs, dotlottie-rs/src/state_machine_engine/interactions/mod.rs, dotlottie-rs/src/state_machine_engine/mod.rs, dotlottie-rs/src/state_machine_engine/security/mod.rs, dotlottie-rs/src/state_machine_engine/state_machine/mod.rs, dotlottie-rs/src/state_machine_engine/states/mod.rs
Refactors error handling by simplifying custom error types and removing unnecessary error detail propagation. This includes:
* Dropping `thiserror` in favor of minimal manual error implementations
* Removing the unused `json` crate
#107
* **Before:** 1,861,156 bytes
* **After:** 1,848,771 bytes
* **Reduction:** **12.3 KB**
=> refactor: simplify error handling and remove unnecessary error details

Makefile
Partial rendering does not provide meaningful benefits for Lottie animations and instead increases the
binary size unnecessarily.
This should be pushed along with throvg v1.0-pre23
=> thorvg: disable partial rendering in the build

dotlottie-rs/src/lottie_renderer/thorvg.rs
Add cfg_attr directives to handle lint warnings for variables that are only used in specific feature configurations (thorvg-v0 vs thorvg-v1).
This prevents `false` positive warnings when building with different feature flags enabled.
=> chore: suppress unused variable warnings for feature-gated code

dotlottie-rs/src/state_machine_engine/mod.rs, dotlottie-rs/src/state_machine_engine/states/mod.rs, dotlottie-rs/tests/play_mode.rs
When the state machine enters a new state, it now preserves the existing layout configuration property from the player instead of overriding it with a default value. This ensures user-configured layout settings are maintained during state transitions, similar to how `use_frame_interpolation` was already being preserved
=> fix: preserve layout property when entering state
